In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

- <font size = 2> I have excel files. Therefore I will use read_excel function of pandas library. </font>

In [2]:
train_df = pd.read_excel("Data_Train.xlsx")
test_df = pd.read_excel("Test_set.xlsx")

- <font size = 2> To decrease the complexity I will merge these two dataframes as a final dataframe "final_df" </font>

In [3]:
final_df = train_df.append(test_df)
final_df.head(2)

C:\Users\Vasif\AppData\Local\Temp\ipykernel_19676\1964040745.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = train_df.append(test_df)


Airline Date_of_Journey    Source Destination                  Route  \
0     IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1  Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info   Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info  3897.0  
1    05:50         13:15   7h 25m     2 stops         No info  7662.0

------------------------------------------------------

- <font size = 2> To get information about the final dataframe, info() function will be used </font>

In [4]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Date_of_Journey  13354 non-null  object 
 2   Source           13354 non-null  object 
 3   Destination      13354 non-null  object 
 4   Route            13353 non-null  object 
 5   Dep_Time         13354 non-null  object 
 6   Arrival_Time     13354 non-null  object 
 7   Duration         13354 non-null  object 
 8   Total_Stops      13353 non-null  object 
 9   Additional_Info  13354 non-null  object 
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.2+ MB


<font size = 2> Our data has the following columns:
- Airline - shows airplane company
- Date of Journey
- Source - shows departure country
- Route - roadmap of flight
- Dep_time - Departure time
- Arrival_time
- Duration - duration of flight
- Total_stops
- Additional_info - comments about flight
- Price - ticket price
</font>

    

<font size=2> We need to see whether any columns have null values or not </font>

In [5]:
final_df.isnull().sum()

Airline               0
Date_of_Journey       0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
dtype: int64

- <font size = 3>The data has special column "Date of Journey". It is given as "Date/Month/Year". I will extract the information from this as separate <i>"Date", "Month","Year" </i> columns </font>

<font size =2>To extract the information from string I will use str.split() function

In [6]:
final_df["Date_of_Journey"].str.split("/")

0       [24, 03, 2019]
1        [1, 05, 2019]
2        [9, 06, 2019]
3       [12, 05, 2019]
4       [01, 03, 2019]
             ...      
2666     [6, 06, 2019]
2667    [27, 03, 2019]
2668     [6, 03, 2019]
2669     [6, 03, 2019]
2670    [15, 06, 2019]
Name: Date_of_Journey, Length: 13354, dtype: object

In [7]:
# Extract date, month and year form df
final_df["Date"] = final_df["Date_of_Journey"].str.split("/").str[0]
final_df["Month"] = final_df["Date_of_Journey"].str.split("/").str[1]
final_df["Year"] = final_df["Date_of_Journey"].str.split("/").str[2]


In [8]:
final_df.head(3)

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info    Price Date  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897.0   24   
1    05:50         13:15   7h 25m     2 stops         No info   7662.0    1   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882.0    9   

  Month  Year  
0    03  2019  
1    05  2019  
2    06  2019

- <font size = 2>After extraction we can see added columns "Date", "Month" and "Year". However, they are object types, and therefore it is required to convert them into integer values. To do that I will use <i> **astype function** </i> </font>

In [9]:
final_df["Date"] = final_df["Date"].astype(int)
final_df['Month']=final_df['Month'].astype(int)
final_df['Year']=final_df['Year'].astype(int)

- <font size = 2> I got the columns of date, and therefore there is no need to have *"Date of Journey"* column. Therefore, just drop it. </font>

In [10]:
final_df.drop("Date_of_Journey", axis = 1, inplace = True)

In [11]:
final_df.head(3)

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   

   Arrival_Time Duration Total_Stops Additional_Info    Price  Date  Month  \
0  01:10 22 Mar   2h 50m    non-stop         No info   3897.0    24      3   
1         13:15   7h 25m     2 stops         No info   7662.0     1      5   
2  04:25 10 Jun      19h     2 stops         No info  13882.0     9      6   

   Year  
0  2019  
1  2019  
2  2019

- <font size = 2> Now I will start to analyse "Arrival time" feature. This column has three parts. First part shows the time, second part shows the arrival day and third one shows the arrival month -> [01:10  22 Mar].
They are separated with blank space. We should extract the time information from it. That's why, I will again use *str.split()* function </font>

In [12]:
final_df["Arrival_clock"] = final_df["Arrival_Time"].str.split().str[0]
final_df[["Arrival_clock"]].head(3)

Arrival_clock
0         01:10
1         13:15
2         04:25

- <font size = 2> It is possible to even extract the exact hour and minutes from this *arrival_hour* data by using the same function. </font>

In [13]:
#Extracting hour from clock
final_df["Arrival_hour"] = final_df["Arrival_clock"].str.split(":").str[0]
final_df["Arrival_hour"].head(3)

0    01
1    13
2    04
Name: Arrival_hour, dtype: object

In [14]:
#Extracting minutes from clock
final_df["Arrival_min"] = final_df["Arrival_clock"].str.split(":").str[1]
final_df["Arrival_min"].head(3)

0    10
1    15
2    25
Name: Arrival_min, dtype: object

<font size=3> <font color = Red> Instead of str.split() function we can use **lambda** function , too </font></font>

In [ ]:
final_df["Arrival_min"] = final_df["Arrival_clock"].apply(lambda x: x.split(":")[1])
final_df["Arrival_min"].head(3)

- <font size =3> As is seen from the results following two functions give the same results:
    - <b>df["column"].apply(lambda x: x.split(":")[0])
    - <b>df["column"].str.split(":").str[0]

In [15]:
final_df.head(3)

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   

   Arrival_Time Duration Total_Stops Additional_Info    Price  Date  Month  \
0  01:10 22 Mar   2h 50m    non-stop         No info   3897.0    24      3   
1         13:15   7h 25m     2 stops         No info   7662.0     1      5   
2  04:25 10 Jun      19h     2 stops         No info  13882.0     9      6   

   Year Arrival_clock Arrival_hour Arrival_min  
0  2019         01:10           01          10  
1  2019         13:15           13          15  
2  2019         04:25           04          25

- <font size= 2> ***"Arrival hour"*** and ***"arrival minutes"*** are object types. They must be converted to integer. Use *astype* function. </font>

In [17]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Source           13354 non-null  object 
 2   Destination      13354 non-null  object 
 3   Route            13353 non-null  object 
 4   Dep_Time         13354 non-null  object 
 5   Arrival_Time     13354 non-null  object 
 6   Duration         13354 non-null  object 
 7   Total_Stops      13353 non-null  object 
 8   Additional_Info  13354 non-null  object 
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int32  
 11  Month            13354 non-null  int32  
 12  Year             13354 non-null  int32  
 13  Arrival_clock    13354 non-null  object 
 14  Arrival_hour     13354 non-null  int32  
 15  Arrival_min      13354 non-null  int32  
dtypes: float64(1), int32(5), object(10)
memory usage: 1.5+ MB


In [16]:
final_df["Arrival_hour"] = final_df["Arrival_hour"].astype(int)
final_df["Arrival_min"] = final_df["Arrival_min"].astype(int)

In [18]:
final_df[["Arrival_hour","Arrival_min"]].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Arrival_hour  13354 non-null  int32
 1   Arrival_min   13354 non-null  int32
dtypes: int32(2)
memory usage: 208.7 KB


- <font size = 2>I will not use ***"Arrival clock"*** and ***"Arrival Time"*** information, therefore just drop them </font>

In [19]:
final_df.drop("Arrival_clock",axis=1,inplace=True)

In [20]:
final_df.drop("Arrival_Time",axis=1,inplace=True)

In [21]:
final_df.head(3)

Airline    Source Destination                  Route Dep_Time Duration  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   2h 50m   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   7h 25m   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25      19h   

  Total_Stops Additional_Info    Price  Date  Month  Year  Arrival_hour  \
0    non-stop         No info   3897.0    24      3  2019             1   
1     2 stops         No info   7662.0     1      5  2019            13   
2     2 stops         No info  13882.0     9      6  2019             4   

   Arrival_min  
0           10  
1           15  
2           25

- <font size = 2> I will apply the same process to the ***Departure Time*** column

In [22]:
final_df["Dept_hour"] = final_df["Dep_Time"].str.split(":").str[0]
final_df["Dept_min"] = final_df["Dep_Time"].str.split(":").str[1]
final_df['Dept_hour']=final_df['Dept_hour'].astype(int)
final_df['Dept_min']=final_df['Dept_min'].astype(int)
final_df.drop('Dep_Time',axis=1,inplace=True)

In [23]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Source           13354 non-null  object 
 2   Destination      13354 non-null  object 
 3   Route            13353 non-null  object 
 4   Duration         13354 non-null  object 
 5   Total_Stops      13353 non-null  object 
 6   Additional_Info  13354 non-null  object 
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int32  
 9   Month            13354 non-null  int32  
 10  Year             13354 non-null  int32  
 11  Arrival_hour     13354 non-null  int32  
 12  Arrival_min      13354 non-null  int32  
 13  Dept_hour        13354 non-null  int32  
 14  Dept_min         13354 non-null  int32  
dtypes: float64(1), int32(7), object(7)
memory usage: 1.3+ MB


- <font size = 3> After solving date/time/hour problems, we can deal with remanining columns. Let's now think what we can do with the ***Total_stops*** column. We can see values of these column by using **unique()** function: </font>

In [24]:
final_df["Total_Stops"].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

<font size =2> We can see it has 6 object type unique values. In the model training, working with object data types is very difficult, therefore it is preffered to convert object types to integer types somehow. Here, we can use only the integer numbers which represents the number of stops. To do that we can use **map** function to write integers instead of strings:
- non-stop:0
- 1 stop: 1
- 2 stops: 2
- 3 stops: 3
- 4 stops: 4
- nan: 1
Let's apply it with map function </font>

In [25]:
final_df["Total_Stops"] = final_df["Total_Stops"].map({"non-stop":0, "1 stop":1, "2 stops": 2, "3 stops":3, "4 stops":4, "nan":1})

In [26]:
final_df[["Total_Stops"]].head(3)

Total_Stops
0          0.0
1          2.0
2          2.0

- <font size =2> ***Route*** column does not have necessary information. Therefore, drop it!


In [27]:
final_df.drop("Route", axis=1,inplace=True)

In [28]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Source           13354 non-null  object 
 2   Destination      13354 non-null  object 
 3   Duration         13354 non-null  object 
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object 
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int32  
 8   Month            13354 non-null  int32  
 9   Year             13354 non-null  int32  
 10  Arrival_hour     13354 non-null  int32  
 11  Arrival_min      13354 non-null  int32  
 12  Dept_hour        13354 non-null  int32  
 13  Dept_min         13354 non-null  int32  
dtypes: float64(2), int32(7), object(5)
memory usage: 1.2+ MB


- <font size =2> Analyse ***Additional_Info*** column: </font>

In [29]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

- <font size =2> Let's now convert the values from ***Duration*** column to ***Duration_minutes*** with minutes. Hours will be converted to minutes and will be summed up with given minutes. As an example, the value of [2h 50m] will be [(2*60 + 50)m = 170 m]

<font size = 2> To do that, the hours and minutes must be extracted from the duration value. Again we will apply str.split() function.


In [30]:
hours = np.array(int)
minutes = np.array(int)

In [45]:
# extracted_hour = final_df["Duration"].str.split(" ").str[0] --> 2h
# extracted_hour_number = extracted_hour.str.split("h").str[0] --> 2

hours = final_df["Duration"].str.split(" ").str[0].str.split("h").str[0]

In [46]:
hours.isnull().sum()

0

In [37]:
minutes = final_df["Duration"].str.split(" ").str[1].str.split("m").str[0]

- <font size=2> Now turn dtype from object to integer </font>

<font size = 3> Before converting to integer, we should fill the NaN values in minutes array with 0. I will use ***fillna()*** function to do this.

In [39]:
minutes = minutes.fillna(0)
minutes.isnull().sum()

0

In [40]:
final_df[final_df["Duration"] == "5m"]

Airline  Source Destination Duration  Total_Stops Additional_Info  \
6474  Air India  Mumbai   Hyderabad       5m          2.0         No info   
2660  Air India  Mumbai   Hyderabad       5m          2.0         No info   

        Price  Date  Month  Year  Arrival_hour  Arrival_min  Dept_hour  \
6474  17327.0     6      3  2019            16           55         16   
2660      NaN    12      3  2019            16           55         16   

      Dept_min  
6474        50  
2660        50

- <font size = 2> we can see that in the 6474 and 2660 rows, Duration is 5m. This 5m was added to hours array. But they must be added to minutes array. We can change it manually with the following code </font>

In [50]:
hours[6474] = 0
hours[2660] = 0
minutes[6470] = 5
hours[6470] = 5

In [ ]:
#We can either remove the rows with 5m duration time
#final_df.drop(6474,axis=0,inplace=True)
#final_df.drop(2660,axis=0,inplace=True)

In [51]:
hours = hours.astype(int)
minutes = minutes.astype(int)

In [52]:
duration_min = np.array(int)
duration_min = hours*60+minutes

final_df["Duration_minutes"] = duration_min

In [53]:
final_df["Duration_minutes"].head()

0     170
1     445
2    1140
3     325
4     285
Name: Duration_minutes, dtype: int32

In [54]:
final_df.drop("Duration",axis=1,inplace=True)

final_df.head()

Airline    Source Destination  Total_Stops Additional_Info    Price  \
0       IndiGo  Banglore   New Delhi          0.0         No info   3897.0   
1    Air India   Kolkata    Banglore          2.0         No info   7662.0   
2  Jet Airways     Delhi      Cochin          2.0         No info  13882.0   
3       IndiGo   Kolkata    Banglore          1.0         No info   6218.0   
4       IndiGo  Banglore   New Delhi          1.0         No info  13302.0   

   Date  Month  Year  Arrival_hour  Arrival_min  Dept_hour  Dept_min  \
0    24      3  2019             1           10         22        20   
1     1      5  2019            13           15          5        50   
2     9      6  2019             4           25          9        25   
3    12      5  2019            23           30         18         5   
4     1      3  2019            21           35         16        50   

   Duration_minutes  
0               170  
1               445  
2              1140  
3               325  
4               285

- <font size=2>Remaining columns are object types and can only be converted to dummy variables. Or we can use **LabelEncoder** or **OneHotEncoder**</font>

In [55]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [57]:
final_df["Airline"] = labelencoder.fit_transform(final_df["Airline"])
final_df["Source"] = labelencoder.fit_transform(final_df["Source"])
final_df["Destination"] = labelencoder.fit_transform(final_df["Destination"])
final_df["Additional_Info"] = labelencoder.fit_transform(final_df["Additional_Info"])


In [ ]:
final_df["Airline"].unique()

In [58]:
final_df.head()

Airline  Source  Destination  Total_Stops  Additional_Info    Price  Date  \
0        3       0            5          0.0                8   3897.0    24   
1        1       3            0          2.0                8   7662.0     1   
2        4       2            1          2.0                8  13882.0     9   
3        3       3            0          1.0                8   6218.0    12   
4        3       0            5          1.0                8  13302.0     1   

   Month  Year  Arrival_hour  Arrival_min  Dept_hour  Dept_min  \
0      3  2019             1           10         22        20   
1      5  2019            13           15          5        50   
2      6  2019             4           25          9        25   
3      5  2019            23           30         18         5   
4      3  2019            21           35         16        50   

   Duration_minutes  
0               170  
1               445  
2              1140  
3               325  
4               285

In [59]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Airline           13354 non-null  int64  
 1   Source            13354 non-null  int64  
 2   Destination       13354 non-null  int64  
 3   Total_Stops       13353 non-null  float64
 4   Additional_Info   13354 non-null  int64  
 5   Price             10683 non-null  float64
 6   Date              13354 non-null  int32  
 7   Month             13354 non-null  int32  
 8   Year              13354 non-null  int32  
 9   Arrival_hour      13354 non-null  int32  
 10  Arrival_min       13354 non-null  int32  
 11  Dept_hour         13354 non-null  int32  
 12  Dept_min          13354 non-null  int32  
 13  Duration_minutes  13354 non-null  int32  
dtypes: float64(2), int32(8), int64(4)
memory usage: 1.6 MB


<font size = 4> <b> Finally, analysing the data is finished and the data is now ready for the model training </b>